### ISSUE TITLE
is it possible to add tag depending on match?

### ISSUE THREAD

**Issue by vaidas-lungis** [patant/fluent-plugin-loggly#14]
```
  <match your_match>
      type loggly
      loggly_url https://logs-01.loggly.com/inputs/xxx-xxxx-xxxx-xxxxx-xxxxxxxxxx
  </match>
```
it will post messages to http tag on loggly system by default. or it set tag if /tag/[you-tag] appended to loggly_url   
Is it possible to post messages to matched tag?

**Comment by patant** [comment]
Not sure what you looking for. 
But if you need diffrent tags just add multiple match with the tag(s).

Tags added to loggly accordingly to https://www.loggly.com/docs/tags/

**Comment by vaidas-lungis** [comment]
I think i was looking something like this
https://gist.github.com/sobstel/9bb797e46b1838797a8c
