### ISSUE TITLE
Upgrade to fluentd 0.14 API

### ISSUE THREAD

**Issue by njam** [patant/fluent-plugin-loggly#19]
Fluentd 0.14 introduced a new plugin API: http://www.fluentd.org/blog/fluentd-v0.14.0-has-been-released

It would be great if I could use the new "dynamic configurations":

> support formatting configurations dynamically (e.g., `path /my/dest/${tag}/mydata.%Y-%m-%d.log`)

This way I could use my _fluentd tags_ as my _Loggly tags_ by setting the URL to:

```
loggly_url https://logs-01.loggly.com/bulk/xxxxxxxxxxxx/tag/${tag}
```

**Comment by schasse** [comment]
I need this as well. Any updates on this? When do you make new release?

**Comment by njam** [comment]
too old
