### ISSUE TITLE
Dependency error for net-http-persistent

### ISSUE THREAD

**Issue by mostlyjason** [patant/fluent-plugin-loggly#23]
Hi our work with the Loggly team and we just got this bug report from a customer.  We are posting it here because it looks like we need to update a dependency in this library. I pasted his email below. What's the best way to address this?  Would you be open to a pull request that we submit?

"I just pushed a new build of our AMI that uses fluentd to log to Loggly,
and things stopped working. Some diagnosis later, I discovered that a new
version of the 'net-http-persistent' has been released (3.0.0 as opposed to
2.9.4, which was working before), and it looks like the 'initialize'
function of that module doesn't like what the loggly module passes to it.
Here's a stacktrace to show what I'm seeing:

2016-10-13 17:27:17 +0000 [error]: unexpected error
error_class=ArgumentError error=#<ArgumentError: wrong number of
arguments (2 for 0)>
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:505:in
`initialize'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-loggly-0.0.8/lib/fluent/plugin/out_loggly_buffered.rb:43:in
`new'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-loggly-0.0.8/lib/fluent/plugin/out_loggly_buffered.rb:43:in
`start'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/out_copy.rb:55:in
`block in start'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/out_copy.rb:54:in
`each'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/out_copy.rb:54:in
`start'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/agent.rb:70:in
`block in start'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/agent.rb:69:in
`each'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/agent.rb:69:in
`start'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/root_agent.rb:108:in
`start'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/engine.rb:237:in
`start'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/engine.rb:187:in
`run'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:570:in
`run_engine'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:162:in
`block in start'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:366:in
`call'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:366:in
`main_process'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:339:in
`block in supervise'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:338:in
`fork'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:338:in
`supervise'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:156:in
`start'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/command/fluentd.rb:173:in
`<top (required)>'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/bin/fluentd:5:in
`<top (required)>'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/bin/fluentd:23:in `load'
2016-10-13 17:27:17 +0000 [error]:
/opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
2016-10-13 17:27:17 +0000 [error]: /usr/sbin/td-agent:7:in `load'
2016-10-13 17:27:17 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'

*I have a temporary solution - downgrade the net-http-persistent gem in my
environment - and I know this isn't strictly Loggly's problem, but I am
*not* Ruby-friendly and was wondering if an adjustment could be made to the
Loggly fluentd plugin to account for this change in that module's function
signature*."

**Comment by patant** [comment]
Should been fixed with the latest version [0.0.9](https://rubygems.org/gems/fluent-plugin-loggly/versions/0.0.9). See PR #20.

**Comment by sagar-babar** [comment]
No its not yet working after upgrading to 0.0.9

**Comment by patant** [comment]
root@6fa33ea4bce1:/# td-agent --version
td-agent 0.12.29

root@6fa33ea4bce1:/# td-agent-gem install fluent-plugin-loggly
Fetching: net-http-persistent-2.9.4.gem (100%)
Successfully installed net-http-persistent-2.9.4
Fetching: fluent-plugin-loggly-0.0.9.gem (100%)
Successfully installed fluent-plugin-loggly-0.0.9
Parsing documentation for net-http-persistent-2.9.4
Installing ri documentation for net-http-persistent-2.9.4
Parsing documentation for fluent-plugin-loggly-0.0.9
Installing ri documentation for fluent-plugin-loggly-0.0.9
Done installing documentation for net-http-persistent, fluent-plugin-loggly after 0 seconds
2 gems installed

Did a quick test and 0.0.9 does not install net-http-persistent > 3.0.0

**Comment by sagarinitcron** [comment]
@patant  Thanks for your help..!!

Its working but, now i am getting below error
2016-11-10 14:55:50 +0000 [error]: Error connecting to loggly verify the url https://logs-01.loggly.com/bulk/*****************************/tag/ano,dls
2016-11-10 14:55:50 +0000 fluent.error: {"message":"Error connecting to loggly verify the url https://logs-01.loggly.com/bulk/**********************************/tag/ano,dls"}

Could you please help on this.

**Comment by patant** [comment]
@sagarinitcron Check this page and verify your url https://www.loggly.com/docs/http-bulk-endpoint/
